# Generated by Django 4.2 on 2023-04-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0002_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(choices=[('SOL', 'Solteiro'), ('CAS', 'Casado'), ('DIV', 'Divorciado'), ('VIV', 'Viúvo')], max_length=3, null=True),
        ),
    ]
