# Generated by Django 4.2 on 2023-05-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0009_cliente_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Usuário Ativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matricula',
            field=models.IntegerField(verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.profissao', verbose_name='Profissão'),
        ),
    ]
